services:
  postgres:
    image: postgres:16-alpine
    container_name: glasify_postgres_db
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  postgres_network:
    name: postgres_network
